# Generated by Django 5.1.5 on 2025-02-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('warehouse_staff', 'Warehouse Staff'), ('management', 'Management')], default='driver', max_length=20),
        ),
    ]
